routes/web.php
<?php

use App\Http\Controllers\CleanTweetController;
use App\Http\Controllers\FakeTweetController;
use App\Http\Controllers\FollowController;
use App\Http\Controllers\RetweetController;
use App\Http\Controllers\TweetController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('users', UserController::class)->only(['index', 'show']);
Route::resource('tweets', TweetController::class)->only(['index', 'create', 'store']);
Route::resource('follows', FollowController::class)->only(['index', 'store', 'destroy']);
Route::resource('retweets', RetweetController::class)->only(['store']);
Route::resource('fake-tweets', FakeTweetController::class)->middleware('admin')->only(['create', 'store']);
Route::resource('clean-tweets', CleanTweetController::class)->only(['create', 'store']);

require __DIR__.'/auth.php';

app/Models/Follow.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Follow extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'leader_id',
        'follower_id',
    ];
}

app/Http/Controllers/FollowController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreFollowRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Lang;
use Illuminate\View\View;

class FollowController extends Controller
{
    /**
     * Display a listing of people that current user follows.
     *
     * @return View
     */
    public function index(): View
    {
        $followedByUser = Auth::user()->following()->paginate(5);

        return view('follows.index')->with(['followedByUser' => $followedByUser]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreFollowRequest $request
     * @return RedirectResponse
     */
    public function store(StoreFollowRequest $request): RedirectResponse
    {
        Auth::user()->following()->attach($request->only(['leader_id']));

        return redirect()->back()->with(['message' => Lang::get('Successfully followed')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $follow
     * @return RedirectResponse
     */
    public function destroy(int $follow): RedirectResponse
    {
        Auth::user()->following()->detach($follow);

        return redirect()->back()->with(['message' => Lang::get('Successfully unfollowed')]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/follows/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Show all users that I follow') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                @foreach($followedByUser AS $user)
                    <div class="p-6 bg-white border-b border-gray-200">
                        {{$user->name}}  </br>

                        {{$user->email}}

                        <form method="POST" action="{{ route('follows.destroy', ['follow' => $user->id]) }}">
                            @csrf
                            @method('DELETE')
                            <x-button class="ml-3">
                                {{ __('Unfollow') }}
                            </x-button>
                        </form>
                    </div>
                @endforeach

            </div>

            {{ $followedByUser->links() }}
        </div>
    </div>
</x-app-layout>