routes/web.php
<?php

use App\Http\Controllers\CleanTweetController;
use App\Http\Controllers\FakeTweetController;
use App\Http\Controllers\FollowController;
use App\Http\Controllers\RetweetController;
use App\Http\Controllers\TweetController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('users', UserController::class)->only(['index', 'show']);
Route::resource('tweets', TweetController::class)->only(['index', 'create', 'store']);
Route::resource('follows', FollowController::class)->only(['index', 'store', 'destroy']);
Route::resource('retweets', RetweetController::class)->only(['store']);
Route::resource('fake-tweets', FakeTweetController::class)->middleware('admin')->only(['create', 'store']);
Route::resource('clean-tweets', CleanTweetController::class)->only(['create', 'store']);

require __DIR__.'/auth.php';

app/Http/Controllers/FakeTweetController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreFakeTweetRequest;
use App\Models\Tweet;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class FakeTweetController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $users = User::where('id', '!=', Auth::user()->id)->get();

        return view('fake-tweets.create')->with(['users' => $users]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreFakeTweetRequest $request
     * @return RedirectResponse
     */
    public function store(StoreFakeTweetRequest $request): RedirectResponse
    {
        $user = User::where('username', $request->username)->first();

        Tweet::create([
            'title' => $request->title,
            'description' => $request->description,
            'user_id' => $user->id
        ]);

        return redirect()->route('tweets.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/fake-tweets/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Fake Tweet') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('fake-tweets.store') }}">
                    @csrf

                    <!-- Title -->
                        <div>
                            <x-label for="title" :value="__('Title')" />

                            <x-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')" required autofocus />
                        </div>

                        <!-- Description -->
                        <div class="mt-4">
                            <x-label for="description" :value="__('Description')" />

                            <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="old('description')" required />
                        </div> <br>

                        <select name="username" id="username">
                            <option value="0" > Default </option>
                            @foreach($users AS $user)
                            <option value="{{$user->username}}" > {{$user->username}} </option>
                            @endforeach
                        </select>

                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>