routes/web.php
<?php

use App\Http\Controllers\CleanTweetController;
use App\Http\Controllers\FakeTweetController;
use App\Http\Controllers\FollowController;
use App\Http\Controllers\RetweetController;
use App\Http\Controllers\TweetController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('users', UserController::class)->only(['index', 'show']);
Route::resource('tweets', TweetController::class)->only(['index', 'create', 'store']);
Route::resource('follows', FollowController::class)->only(['index', 'store', 'destroy']);
Route::resource('retweets', RetweetController::class)->only(['store']);
Route::resource('fake-tweets', FakeTweetController::class)->middleware('admin')->only(['create', 'store']);
Route::resource('clean-tweets', CleanTweetController::class)->only(['create', 'store']);

require __DIR__.'/auth.php';

app/Models/Tweet.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Tweet extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'description',
        'user_id',
    ];

    #region Relationships
    /**
     * Get tweet author.
     *
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
    #endregion

    #region Scopes

    /**
     * We need to order by tweets by most influence leader.
     *
     * @param Builder $query
     * @param User $user
     * @return Builder
     */
    public function scopeOrderByLeaderInfluence(Builder $query, User $user): Builder
    {
        $getUsersWithMostInfluence = $user->getLeadersOrderedByInfluence();

        return $query
                ->whereIn('user_id', array_column($getUsersWithMostInfluence, 'id'))
                ->orderByRaw("FIELD(user_id, ". implode(',', array_column($getUsersWithMostInfluence, 'id')) .")");
    }

    /**
     * Return newest tweets. Newest tweets are tweets created day before and newer.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeNewest(Builder $query): Builder
    {
        return $query->where('created_at', '>=', Carbon::now()->subDay()->toDateString());
    }
    #endregion
}

app/Http/Controllers/TweetController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTweetRequest;
use App\Models\Tweet;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class TweetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $tweets = Tweet::with('user')
                        ->newest()
                        ->orderByLeaderInfluence(Auth::user())
                        ->paginate(5);

        return view('tweets.index')->with(['tweets' => $tweets]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('tweets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreTweetRequest $request
     * @return RedirectResponse
     */
    public function store(StoreTweetRequest $request): RedirectResponse
    {
        $request->merge(['user_id' => $request->user()->id]);

        Tweet::create($request->only(['title', 'description', 'user_id']));

        return redirect()->route('users.show', ['user' => Auth::user()]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/tweets/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Tweet') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('tweets.store') }}">
                    @csrf

                        <!-- Title -->
                        <div>
                            <x-label for="title" :value="__('Title')" />

                            <x-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')" required autofocus />
                        </div>

                        <!-- Description -->
                        <div class="mt-4">
                            <x-label for="description" :value="__('Description')" />

                            <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="old('description')" required />
                        </div>

                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/tweets/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Tweeter feed') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                @foreach($tweets AS $tweet)
                    <div class="p-6 bg-white border-b border-gray-200">

                        <div class="p-6 bg-white border-b border-gray-200">
                            {{__('Title: ')}} {{$tweet->title}}  <br>

                            {{__('Description: ')}} {{$tweet->description}} <br>

                            {{__('Author: ')}} {{$tweet->user->username}}
                        </div>

                        <form method="POST" action="{{ route('retweets.store') }}">
                            @csrf

                            <input type="hidden" value="{{$tweet->user->id}}" name="user_id" id="user_id">
                            <input type="hidden" value="{{$tweet->id}}" name="tweet_id" id="tweet_id">

                            <x-button class="ml-3">
                                {{ __('Retweet') }}
                            </x-button>
                        </form>

                    </div>
                @endforeach

            </div>

            {{ $tweets->links() }}
        </div>
    </div>
</x-app-layout>